apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: kirtigupta1234/myapp:9
          ports:
            - containerPort: 8080
